# Generated by Django 5.0.7 on 2025-06-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_attendance_extra_time_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('Employee_class', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Employees/')),
                ('authorized', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.employee'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
