# Generated by Django 5.0.7 on 2025-06-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_employee_remove_attendance_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Employee_class',
            new_name='Employee_Id',
        ),
    ]
