# Generated by Django 5.0.7 on 2025-06-18 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_rename_employee_class_employee_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='Employee',
            new_name='employee',
        ),
    ]
