# Generated by Django 5.0.7 on 2025-06-22 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_employee_user_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
