# Generated by Django 5.0.7 on 2025-06-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
